on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Compile code
      run: yarn tsc

    - name: Zip dist folder
      run: |
        cd dist
        zip -r dist.zip .

    - name: Update lambda code
      run: |
        aws lambda update-function-code --function-name felps --zip-file fileb://dist/dist.zip
